#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# Defaults (can be overridden by environment variables)
ENABLE_OPENMP="${ENABLE_OPENMP:-ON}"
ENABLE_CUDA="${ENABLE_CUDA:-ON}"
BUILD_DIR="${BUILD_DIR:-build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
PROBLEM="${PROBLEM:-BrioWuShocktube}"
BUILD_JOBS="${BUILD_JOBS:-$(nproc)}"
CMAKE_GENERATOR="${CMAKE_GENERATOR:-}"
KOKKOS_ARCH="${KOKKOS_ARCH:-}"
CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS:-}"

if [[ "$ENABLE_OPENMP" != "ON" && "$ENABLE_OPENMP" != "OFF" ]]; then
  echo "ERROR: ENABLE_OPENMP must be ON or OFF"
  exit 1
fi
if [[ "$ENABLE_CUDA" != "ON" && "$ENABLE_CUDA" != "OFF" ]]; then
  echo "ERROR: ENABLE_CUDA must be ON or OFF"
  exit 1
fi

cmake_args=(
  -S .
  -B "$BUILD_DIR"
  -DPROBLEM="$PROBLEM"
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
  -DKokkos_ENABLE_OPENMP="$ENABLE_OPENMP"
  -DKokkos_ENABLE_CUDA="$ENABLE_CUDA"
)

if [[ -n "$CMAKE_GENERATOR" ]]; then
  cmake_args+=(-G "$CMAKE_GENERATOR")
fi

if [[ -n "$KOKKOS_ARCH" ]]; then
  cmake_args+=(-DKokkos_ARCH_"$KOKKOS_ARCH"=ON)
fi

if [[ -n "$CMAKE_EXTRA_ARGS" ]]; then
  # shellcheck disable=SC2206
  extra_args=( $CMAKE_EXTRA_ARGS )
  cmake_args+=("${extra_args[@]}")
fi

echo "[make.sh] Configuring project"
cmake "${cmake_args[@]}"

echo "[make.sh] Building project"
cmake --build "$BUILD_DIR" -j "$BUILD_JOBS"

if [[ "$ENABLE_CUDA" == "ON" ]]; then
  exe_name="pangu.cuda"
else
  exe_name="pangu.host"
fi

exe_path="$BUILD_DIR/pangu/src/$exe_name"

if [[ ! -x "$exe_path" ]]; then
  echo "ERROR: Build finished but executable not found: $exe_path"
  exit 2
fi

cat > .pangu_build.env <<EOF
# Auto-generated by make.sh
BUILD_DIR=$BUILD_DIR
BUILD_TYPE=$BUILD_TYPE
PROBLEM=$PROBLEM
ENABLE_OPENMP=$ENABLE_OPENMP
ENABLE_CUDA=$ENABLE_CUDA
EXE_NAME=$exe_name
EXE_PATH=$exe_path
EOF

echo "[make.sh] Done"
echo "[make.sh] Executable: $exe_path"
echo "[make.sh] Build config saved to .pangu_build.env"
