#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# Defaults (can be overridden by environment variables)
ENABLE_OPENMP="${ENABLE_OPENMP:-ON}"
ENABLE_CUDA="${ENABLE_CUDA:-ON}"
BUILD_DIR="${BUILD_DIR:-build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
PROBLEM="${PROBLEM:-shock_tube}"
BUILD_JOBS="${BUILD_JOBS:-4}"
CMAKE_GENERATOR="${CMAKE_GENERATOR:-}"
KOKKOS_ARCH="${KOKKOS_ARCH:-}"
CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS:-}"
PROBLEM_PROXY_MODE="${PROBLEM_PROXY_MODE:-ON}"
PROBLEM_PROXY_NAME="${PROBLEM_PROXY_NAME:-__active_problem__}"
NUM_GPU_DEVICES_PER_NODE="${NUM_GPU_DEVICES_PER_NODE:-1}"
PARTHENON_ENABLE_HOST_COMM_BUFFERS="${PARTHENON_ENABLE_HOST_COMM_BUFFERS:-OFF}"

if [[ "$ENABLE_OPENMP" != "ON" && "$ENABLE_OPENMP" != "OFF" ]]; then
  echo "ERROR: ENABLE_OPENMP must be ON or OFF"
  exit 1
fi
if [[ "$ENABLE_CUDA" != "ON" && "$ENABLE_CUDA" != "OFF" ]]; then
  echo "ERROR: ENABLE_CUDA must be ON or OFF"
  exit 1
fi
if [[ "$PROBLEM_PROXY_MODE" != "ON" && "$PROBLEM_PROXY_MODE" != "OFF" ]]; then
  echo "ERROR: PROBLEM_PROXY_MODE must be ON or OFF"
  exit 1
fi

actual_problem_src="$ROOT_DIR/pangu/problem/$PROBLEM/problem_generator.cpp"
if [[ ! -f "$actual_problem_src" ]]; then
  echo "ERROR: Problem source not found: $actual_problem_src"
  exit 1
fi

PROBLEM_CMAKE_VALUE="$PROBLEM"
if [[ "$PROBLEM_PROXY_MODE" == "ON" ]]; then
  if [[ "$PROBLEM" == "$PROBLEM_PROXY_NAME" ]]; then
    echo "ERROR: PROBLEM cannot be the same as PROBLEM_PROXY_NAME when proxy mode is ON"
    exit 1
  fi

  proxy_dir="$ROOT_DIR/pangu/problem/$PROBLEM_PROXY_NAME"
  proxy_src="$proxy_dir/problem_generator.cpp"
  proxy_include_rel="../$PROBLEM/problem_generator.cpp"

  mkdir -p "$proxy_dir"
  tmp_proxy="$(mktemp "$proxy_dir/.problem_generator.cpp.XXXXXX")"
  cat > "$tmp_proxy" <<EOF
// Auto-generated by scripts/shell/make.sh. Do not edit.
// Keeps CMake PROBLEM cache stable to avoid full reconfigure when switching problems.
#include "$proxy_include_rel"
EOF

  if [[ ! -f "$proxy_src" ]] || ! cmp -s "$tmp_proxy" "$proxy_src"; then
    mv "$tmp_proxy" "$proxy_src"
    echo "[make.sh] Updated problem proxy: $proxy_src -> $PROBLEM"
  else
    rm -f "$tmp_proxy"
  fi

  PROBLEM_CMAKE_VALUE="$PROBLEM_PROXY_NAME"
fi

cmake_args=(
  -S .
  -B "$BUILD_DIR"
  -DPROBLEM="$PROBLEM_CMAKE_VALUE"
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
  -DKokkos_ENABLE_OPENMP="$ENABLE_OPENMP"
  -DKokkos_ENABLE_CUDA="$ENABLE_CUDA"
  -DNUM_GPU_DEVICES_PER_NODE="$NUM_GPU_DEVICES_PER_NODE"
  -DPARTHENON_ENABLE_HOST_COMM_BUFFERS="$PARTHENON_ENABLE_HOST_COMM_BUFFERS"
)

if [[ -n "$CMAKE_GENERATOR" ]]; then
  cmake_args+=(-G "$CMAKE_GENERATOR")
fi

if [[ -n "$KOKKOS_ARCH" ]]; then
  cmake_args+=(-DKokkos_ARCH_"$KOKKOS_ARCH"=ON)
fi

if [[ -n "$CMAKE_EXTRA_ARGS" ]]; then
  # shellcheck disable=SC2206
  extra_args=( $CMAKE_EXTRA_ARGS )
  cmake_args+=("${extra_args[@]}")
fi

mkdir -p "$BUILD_DIR"

config_stamp="$BUILD_DIR/.pangu_cmake_config"
tmp_config="$(mktemp "$BUILD_DIR/.pangu_cmake_config.XXXXXX")"
cat > "$tmp_config" <<EOF
ENABLE_OPENMP=$ENABLE_OPENMP
ENABLE_CUDA=$ENABLE_CUDA
BUILD_TYPE=$BUILD_TYPE
PROBLEM_CMAKE_VALUE=$PROBLEM_CMAKE_VALUE
CMAKE_GENERATOR=$CMAKE_GENERATOR
KOKKOS_ARCH=$KOKKOS_ARCH
CMAKE_EXTRA_ARGS=$CMAKE_EXTRA_ARGS
EOF

need_configure="ON"
if [[ -f "$BUILD_DIR/CMakeCache.txt" && -f "$config_stamp" ]] && cmp -s "$tmp_config" "$config_stamp"; then
  need_configure="OFF"
fi

if [[ "$need_configure" == "ON" ]]; then
  echo "[make.sh] Configuring project"
  cmake "${cmake_args[@]}"
  mv "$tmp_config" "$config_stamp"
else
  rm -f "$tmp_config"
  echo "[make.sh] Reusing existing CMake configuration (no reconfigure needed)"
fi

echo "[make.sh] Building project"
cmake --build "$BUILD_DIR" -j "$BUILD_JOBS"

simulator_mode="GRMHD"

if [[ "$ENABLE_CUDA" == "ON" ]]; then
  exe_name="pangu.cuda"
else
  exe_name="pangu.host"
fi

exe_path="$BUILD_DIR/pangu/src/$exe_name"

if [[ ! -x "$exe_path" ]]; then
  echo "ERROR: Build finished but executable not found: $exe_path"
  exit 2
fi

cat > .pangu_build.env <<EOF
# Auto-generated by make.sh
BUILD_DIR=$BUILD_DIR
BUILD_TYPE=$BUILD_TYPE
PROBLEM=$PROBLEM
PROBLEM_CMAKE_VALUE=$PROBLEM_CMAKE_VALUE
PROBLEM_PROXY_MODE=$PROBLEM_PROXY_MODE
SIMULATOR_MODE=$simulator_mode
ENABLE_OPENMP=$ENABLE_OPENMP
ENABLE_CUDA=$ENABLE_CUDA
EXE_NAME=$exe_name
EXE_PATH=$exe_path
EOF

echo "[make.sh] Done"
echo "[make.sh] Simulator mode: $simulator_mode"
echo "[make.sh] Executable: $exe_path"
echo "[make.sh] Build config saved to .pangu_build.env"
