include_guard(GLOBAL)

set(PANGU_PLUGIN_API_VERSION 1)
set(PANGU_PLUGIN_PATHS "" CACHE STRING
    "Semicolon-separated plugin directories or parent directories")

function(pangu_register_plugin)
  set(one_value NAME VERSION REQUIRES_PANGU_API HEADER TYPE DESCRIPTION)
  set(multi_value SOURCES REQUIRES_PLUGIN REQUIRES_CAPABILITY PROVIDES_CAPABILITY CONFLICTS_PLUGIN)
  cmake_parse_arguments(PLUGIN "" "${one_value}" "${multi_value}" ${ARGN})

  foreach(required NAME VERSION REQUIRES_PANGU_API HEADER TYPE)
    if(NOT PLUGIN_${required})
      message(FATAL_ERROR "Plugin manifest ${CMAKE_CURRENT_LIST_FILE} is missing ${required}")
    endif()
  endforeach()
  if(NOT PLUGIN_NAME MATCHES "^[a-z][a-z0-9_-]*$")
    message(FATAL_ERROR "Invalid plugin name '${PLUGIN_NAME}'; use lowercase letters, digits, _ or -")
  endif()
  if(NOT PLUGIN_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "Plugin ${PLUGIN_NAME} has invalid VERSION '${PLUGIN_VERSION}'")
  endif()
  if(NOT PLUGIN_REQUIRES_PANGU_API EQUAL PANGU_PLUGIN_API_VERSION)
    message(FATAL_ERROR
      "Plugin ${PLUGIN_NAME} requires PANGU plugin API ${PLUGIN_REQUIRES_PANGU_API}, "
      "but this build provides ${PANGU_PLUGIN_API_VERSION}")
  endif()

  get_property(names GLOBAL PROPERTY PANGU_PLUGIN_NAMES)
  if(PLUGIN_NAME IN_LIST names)
    message(FATAL_ERROR "Duplicate plugin '${PLUGIN_NAME}' in ${CMAKE_CURRENT_LIST_FILE}")
  endif()

  set(root "${PANGU_CURRENT_PLUGIN_ROOT}")
  if(NOT IS_ABSOLUTE "${PLUGIN_HEADER}")
    set(PLUGIN_HEADER "${root}/${PLUGIN_HEADER}")
  endif()
  if(NOT EXISTS "${PLUGIN_HEADER}")
    message(FATAL_ERROR "Plugin ${PLUGIN_NAME} header does not exist: ${PLUGIN_HEADER}")
  endif()
  set(resolved_sources)
  foreach(source IN LISTS PLUGIN_SOURCES)
    if(NOT IS_ABSOLUTE "${source}")
      set(source "${root}/${source}")
    endif()
    if(NOT EXISTS "${source}")
      message(FATAL_ERROR "Plugin ${PLUGIN_NAME} source does not exist: ${source}")
    endif()
    list(APPEND resolved_sources "${source}")
  endforeach()

  set_property(GLOBAL APPEND PROPERTY PANGU_PLUGIN_NAMES "${PLUGIN_NAME}")
  foreach(field VERSION HEADER TYPE DESCRIPTION REQUIRES_PLUGIN REQUIRES_CAPABILITY
                PROVIDES_CAPABILITY CONFLICTS_PLUGIN)
    set_property(GLOBAL PROPERTY "PANGU_PLUGIN_${PLUGIN_NAME}_${field}" "${PLUGIN_${field}}")
  endforeach()
  set_property(GLOBAL PROPERTY "PANGU_PLUGIN_${PLUGIN_NAME}_SOURCES" "${resolved_sources}")
  set_property(GLOBAL PROPERTY "PANGU_PLUGIN_${PLUGIN_NAME}_ROOT" "${root}")
endfunction()

function(_pangu_plugin_dependency requirement out_name out_min out_max)
  if(NOT requirement MATCHES "^([a-z][a-z0-9_-]*)(>=([0-9]+\\.[0-9]+(\\.[0-9]+)?))?(,<([0-9]+\\.[0-9]+(\\.[0-9]+)?))?$" )
    message(FATAL_ERROR "Invalid plugin dependency '${requirement}'; expected name>=x.y,<z.y")
  endif()
  set(${out_name} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  set(${out_min} "${CMAKE_MATCH_3}" PARENT_SCOPE)
  set(${out_max} "${CMAKE_MATCH_6}" PARENT_SCOPE)
endfunction()

function(_pangu_visit_plugin name chain)
  string(MAKE_C_IDENTIFIER "${name}" key)
  get_property(state GLOBAL PROPERTY "PANGU_PLUGIN_VISIT_${key}")
  if(state STREQUAL "visiting")
    message(FATAL_ERROR "Plugin dependency cycle: ${chain}${name}")
  endif()
  if(state STREQUAL "complete")
    return()
  endif()
  set_property(GLOBAL PROPERTY "PANGU_PLUGIN_VISIT_${key}" visiting)
  get_property(requirements GLOBAL PROPERTY "PANGU_PLUGIN_${name}_REQUIRES_PLUGIN")
  foreach(requirement IN LISTS requirements)
    _pangu_plugin_dependency("${requirement}" dependency minimum maximum)
    _pangu_visit_plugin("${dependency}" "${chain}${name} -> ")
  endforeach()
  set_property(GLOBAL PROPERTY "PANGU_PLUGIN_VISIT_${key}" complete)
endfunction()

function(pangu_discover_plugins)
  set_property(GLOBAL PROPERTY PANGU_PLUGIN_NAMES "")
  set(roots)
  if(EXISTS "${CMAKE_SOURCE_DIR}/plugins")
    file(GLOB builtin_manifests CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/plugins/*/plugin.cmake")
    list(APPEND roots ${builtin_manifests})
  endif()
  foreach(path IN LISTS PANGU_PLUGIN_PATHS)
    get_filename_component(path "${path}" ABSOLUTE)
    if(EXISTS "${path}/plugin.cmake")
      list(APPEND roots "${path}/plugin.cmake")
    elseif(IS_DIRECTORY "${path}")
      file(GLOB external_manifests CONFIGURE_DEPENDS "${path}/*/plugin.cmake")
      list(APPEND roots ${external_manifests})
    else()
      message(FATAL_ERROR "PANGU_PLUGIN_PATHS entry does not contain plugin.cmake: ${path}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES roots)
  list(SORT roots)
  foreach(manifest IN LISTS roots)
    get_filename_component(PANGU_CURRENT_PLUGIN_ROOT "${manifest}" DIRECTORY)
    include("${manifest}")
  endforeach()

  get_property(names GLOBAL PROPERTY PANGU_PLUGIN_NAMES)
  foreach(name IN LISTS names)
    string(MAKE_C_IDENTIFIER "${name}" key)
    set_property(GLOBAL PROPERTY "PANGU_PLUGIN_VISIT_${key}" "")
  endforeach()
  foreach(name IN LISTS names)
    get_property(requirements GLOBAL PROPERTY "PANGU_PLUGIN_${name}_REQUIRES_PLUGIN")
    foreach(requirement IN LISTS requirements)
      _pangu_plugin_dependency("${requirement}" dependency minimum maximum)
      if(NOT dependency IN_LIST names)
        message(FATAL_ERROR "Plugin dependency is missing: ${name} -> ${requirement}")
      endif()
      get_property(version GLOBAL PROPERTY "PANGU_PLUGIN_${dependency}_VERSION")
      if(minimum AND version VERSION_LESS minimum)
        message(FATAL_ERROR "Plugin dependency is incompatible: ${name} -> ${requirement}; found ${version}")
      endif()
      if(maximum AND NOT version VERSION_LESS maximum)
        message(FATAL_ERROR "Plugin dependency is incompatible: ${name} -> ${requirement}; found ${version}")
      endif()
    endforeach()
  endforeach()
  foreach(name IN LISTS names)
    _pangu_visit_plugin("${name}" "")
  endforeach()
endfunction()

function(pangu_prepare_plugins out_sources out_include_dirs)
  get_property(names GLOBAL PROPERTY PANGU_PLUGIN_NAMES)
  set(sources)
  set(include_dirs)
  set(generated "${CMAKE_BINARY_DIR}/generated/pangu/plugin_registry.h")
  set(lockfile "${CMAKE_BINARY_DIR}/pangu-plugins.lock")
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated/pangu")
  file(WRITE "${lockfile}" "# Generated by PANGU; records the plugins compiled into this build.\n")
  set(code "#pragma once\n\n#include <vector>\n#include \"pangu/plugin_api/plugin.h\"\n")
  foreach(name IN LISTS names)
    get_property(header GLOBAL PROPERTY "PANGU_PLUGIN_${name}_HEADER")
    string(APPEND code "#include \"${header}\"\n")
    get_property(plugin_sources GLOBAL PROPERTY "PANGU_PLUGIN_${name}_SOURCES")
    get_property(root GLOBAL PROPERTY "PANGU_PLUGIN_${name}_ROOT")
    get_property(version GLOBAL PROPERTY "PANGU_PLUGIN_${name}_VERSION")
    get_property(requirements GLOBAL PROPERTY "PANGU_PLUGIN_${name}_REQUIRES_PLUGIN")
    string(JOIN "," locked_requirements ${requirements})
    file(APPEND "${lockfile}" "${name}==${version}; requires=${locked_requirements}\n")
    list(APPEND sources ${plugin_sources})
    list(APPEND include_dirs "${root}")
  endforeach()
  string(APPEND code "\nnamespace pangu::plugin::generated {\ninline std::vector<PluginEntry> Entries() {\n  return {\n")
  foreach(name IN LISTS names)
    foreach(field VERSION TYPE DESCRIPTION REQUIRES_PLUGIN REQUIRES_CAPABILITY PROVIDES_CAPABILITY CONFLICTS_PLUGIN)
      get_property(${field} GLOBAL PROPERTY "PANGU_PLUGIN_${name}_${field}")
    endforeach()
    set(dependency_names)
    foreach(requirement IN LISTS REQUIRES_PLUGIN)
      _pangu_plugin_dependency("${requirement}" dependency minimum maximum)
      list(APPEND dependency_names "${dependency}")
    endforeach()
    foreach(field dependency_names REQUIRES_PLUGIN REQUIRES_CAPABILITY PROVIDES_CAPABILITY CONFLICTS_PLUGIN)
      set(initializer "")
      foreach(value IN LISTS ${field})
        string(APPEND initializer "\"${value}\",")
      endforeach()
      set(${field}_CPP "{${initializer}}")
    endforeach()
    string(REPLACE "\"" "\\\"" DESCRIPTION "${DESCRIPTION}")
    string(APPEND code
      "    MakeEntry<${TYPE}>(PluginManifest{\"${name}\", \"${VERSION}\", \"${DESCRIPTION}\", ${dependency_names_CPP}, ${REQUIRES_PLUGIN_CPP}, ${REQUIRES_CAPABILITY_CPP}, ${PROVIDES_CAPABILITY_CPP}, ${CONFLICTS_PLUGIN_CPP}}),\n")
  endforeach()
  string(APPEND code "  };\n}\n} // namespace pangu::plugin::generated\n")
  file(WRITE "${generated}" "${code}")
  list(REMOVE_DUPLICATES include_dirs)
  set(${out_sources} "${sources}" PARENT_SCOPE)
  set(${out_include_dirs} "${include_dirs}" PARENT_SCOPE)
endfunction()
